apiVersion: v1
kind: Service
metadata:
  name: library-system-frontend-service
spec:
  selector:
    app: library-system-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort